### ISSUE TITLE
Shiny Preset Style 2023 Refresh

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/bslib#625]
## Goal

Update Shiny component styles to new "shiny" theme with improved accessibility and baseline styles.

Initial work lives in `theme.scss` from https://github.com/rstudio/shiny-examples/pull/212

## Tasks

```[tasklist]
### Baseline `"shiny"` theme
- [x] #627
- [x] #630
- [x] #643
- [x] #644
- [x] #647
- [ ] #711
```

### Input-specific styles

```[tasklist]
#### Sliders
- [ ] https://github.com/rstudio/bslib/pull/650
- [ ] #688
- [ ] #689
- [ ] #691
- [ ] Ensure sliders are keyboard accessible (see [note here](https://github.com/gregswinehart/shiny-examples/blob/942c26c0bdd1a4a765b0b42879af6e6f6c4375f9/081-widgets-gallery/theme.scss#L144))
- [ ] ~Shim slider target area fix in bslib dependent on shiny version~
```

Slider styles (were originally [proposed here](https://github.com/gregswinehart/shiny-examples/blob/942c26c0bdd1a4a765b0b42879af6e6f6c4375f9/081-widgets-gallery/theme.scss#L95-L167) and [the current slider styles patch](https://github.com/rstudio/shiny/blob/main/tools/ion.rangeSlider-patches/0001-Add-skin-customized-for-Shiny.patch))

We didn't change the default `ticks = FALSE` in `sliderInput()` but we would have liked to (or might in a bslib-specific input)

```[tasklist]
### Input updates
- [x] https://github.com/rstudio/bslib/pull/652
- [ ] https://github.com/rstudio/bslib/issues/712
- [x] Update `layout_columns()` to better support inputs
- [x] Can we default to `width: 100%; min-width: 230px` more generally? Explore impact of [this rule](https://github.com/gregswinehart/shiny-examples/blob/942c26c0bdd1a4a765b0b42879af6e6f6c4375f9/081-widgets-gallery/theme.scss#L90-L93)
- [ ] New file upload input that more closely follows [the Bootstrap 5 file input](https://getbootstrap.com/docs/5.0/forms/form-control/#file-input) (see [current input](https://github.com/rstudio/shiny/blob/e7b830755ac6da2773c9ff15fc6f9395c0c4bf87/R/input-file.R#L102C1-L135))
- [ ] New `actionStateButton()`?
- [ ] New support for [Bootstrap Toasts](https://getbootstrap.com/docs/5.3/components/toasts/)
```

### Components

```[tasklist]
#### Tables
- [ ] #665
- [ ] https://github.com/rstudio/DT/pull/1074
- [ ] https://github.com/rstudio/bslib/issues/718
```

```[tasklist]
#### Sidebars
- [ ] #675
```

```[tasklist]
#### Cards
- [ ] https://github.com/rstudio/bslib/issues/703
- [ ] https://github.com/rstudio/bslib/issues/704
```

```[tasklist]
#### Various
- [ ] https://github.com/rstudio/bslib/issues/752
- [ ] https://github.com/rstudio/bslib/issues/753
```

### Higher-level

```[tasklist]
#### Dashboards
- [x] Shiny preset: Page-level styles for dashboard use-cases
- [x] Revisit title styles in `page_sidebar()`
- [ ] https://github.com/rstudio/bslib/issues/757
```

### Documentation

```[tasklist]
### Docs
- [ ] Blog post announcement
- [ ] General shiny preset theme documentation (in `?bs_theme`?)
- [ ] Cool shiny preset stuff like card table-sm class
```
